app/example/articles/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url

from .views import ArticleListView, ArticleDetailView

urlpatterns = [
    url(r'^$', ArticleListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)', ArticleDetailView.as_view(), name='detail'),
]

app/example/urls.py
# -*- coding: utf-8 -*-

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('example.articles.urls', namespace='articles'))
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [url(r'^__debug__/', include(debug_toolbar.urls))]

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/example/accounts/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from model_utils.fields import AutoCreatedField, AutoLastModifiedField

from .managers import AdministratorManager


class Administrator(AbstractBaseUser, PermissionsMixin):
    USERNAME_FIELD = 'email'
    is_staff = True

    email = models.EmailField('メールアドレス', unique=True)
    is_active = models.BooleanField('有効', default=True)
    created_at = AutoCreatedField('作成日時')
    modified_at = AutoLastModifiedField('更新日時')

    objects = AdministratorManager()

    class Meta:
        verbose_name = "管理者"
        verbose_name_plural = "管理者"

    def __unicode__(self):
        return self.email

    def get_full_name(self):
        return self.__unicode__()

    def get_short_name(self):
        return self.__unicode__()

    def save(self, *args, **kwargs):
        self.is_superuser = True
        return super(Administrator, self).save(*args, **kwargs)

app/example/articles/models.py
# -*- coding: utf-8 -*-

from django.db import models
from model_utils.fields import AutoCreatedField, AutoLastModifiedField


class Article(models.Model):
    title = models.CharField('タイトル', max_length=30)
    body = models.TextField('本文')
    created_at = AutoCreatedField('作成日時')
    modified_at = AutoLastModifiedField('更新日時')

    class Meta:
        verbose_name = '記事'
        verbose_name_plural = '記事'

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, verbose_name='記事', related_name='comments')
    comment = models.CharField('コメント', max_length=120)
    created_at = AutoCreatedField('作成日時')

    class Meta:
        verbose_name = 'コメント'
        verbose_name_plural = 'コメント'

    def __str__(self):
        return self.comment

app/example/articles/forms.py
# -*- coding: utf-8 -*-

from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment',)
        widgets = {
            'comment': forms.Textarea()
        }

app/example/articles/views.py
# -*- coding: utf-8 -*-

from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, ListView

from .forms import CommentForm
from .models import Article


class ArticleListView(ListView):
    model = Article
    queryset = Article.objects.order_by('-created_at')
    template_name = "articles/index.html"
    context_object_name = 'artilces'


class ArticleDetailView(CreateView):
    model = Article
    form_class = CommentForm
    template_name = "articles/detail.html"
    context_object_name = 'article'

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data(**kwargs)

        article = self.get_object()
        context['article'] = article
        context['comments'] = article.comments.order_by('-created_at')

        return context

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article_id = self.kwargs['pk']
        comment.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('articles:detail', kwargs={'pk': self.kwargs['pk']})

app/templates/articles/detail.html
{% extends 'base.html' %}
{% load widget_tweaks %}


{% block main %}
    <div><a href="{% url 'articles:index' %}">List</a></div>
    <article>
        <h1>{{ article.title }}</h1>
        <main>
            {{ article.body|linebreaks }}
        </main>
    </article>

    <form method="POST">
        {% csrf_token %}
        <dl>
            <dt>Comment</dt>
            <dd>{% render_field form.comment %}</dd>
        </dl>
        <div><button type="submit">Submit</button></div>
    </form>

    <ul>
        {% for comment in comments %}
            <li>{{ comment.comment }}</li>
        {% endfor %}
    </ul>
{% endblock main %}

app/templates/articles/index.html
{% extends 'base.html' %}


{% block main %}
    <h1>記事一覧</h1>

    <ul>
        {% for article in artilces %}
            <li><a href="{% url 'articles:detail' pk=article.pk %}">{{ article.title }}</a></li>
        {% endfor %}
    </ul>
{% endblock main %}

app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <title>Django Example</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" media="screen">
    </head>
    <body>
        {% block main %}{% endblock main %}
    </body>
</html>